-- 0010 explicit API-role privileges.
-- Hosted Supabase projects created after mid-2025 no longer give anon / authenticated / service_role
-- automatic privileges on new tables, functions and sequences in `public` (local Supabase still does).
-- Every earlier migration assumed those defaults and then revoked what each role must not have.
-- This migration grants exactly the privileges the local, tested database ends up with, so hosted and
-- local behave the same. It is generated from the local catalog; grants are idempotent.

grant delete, insert, references, select, trigger, truncate, update on table public.activity_logs to service_role;
grant references, select, trigger on table public.activity_logs to anon;
grant references, select, trigger on table public.activity_logs to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.agreement_templates to service_role;
grant insert, references, select, trigger, update on table public.agreement_templates to anon;
grant insert, references, select, trigger, update on table public.agreement_templates to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.agreement_versions to service_role;
grant insert, references, select, trigger, update on table public.agreement_versions to anon;
grant insert, references, select, trigger, update on table public.agreement_versions to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.agreements to service_role;
grant insert, references, select, trigger, update on table public.agreements to anon;
grant insert, references, select, trigger, update on table public.agreements to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.announcement_reads to service_role;
grant insert, references, select, trigger on table public.announcement_reads to anon;
grant insert, references, select, trigger on table public.announcement_reads to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.announcements to service_role;
grant insert, references, select, trigger on table public.announcements to anon;
grant insert, references, select, trigger on table public.announcements to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.app_settings to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.charges to service_role;
grant insert, references, select, trigger, update on table public.charges to anon;
grant insert, references, select, trigger, update on table public.charges to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.complaint_media to service_role;
grant insert, references, select, trigger on table public.complaint_media to anon;
grant insert, references, select, trigger on table public.complaint_media to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.complaint_updates to service_role;
grant references, select, trigger on table public.complaint_updates to anon;
grant references, select, trigger on table public.complaint_updates to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.complaints to service_role;
grant insert, references, select, trigger, update on table public.complaints to anon;
grant insert, references, select, trigger, update on table public.complaints to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.consents to service_role;
grant insert, references, select, trigger on table public.consents to anon;
grant insert, references, select, trigger on table public.consents to authenticated;
grant delete, insert, references, select, trigger on table public.deposit_transactions to anon;
grant delete, insert, references, select, trigger on table public.deposit_transactions to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.deposit_transactions to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.domestic_help to service_role;
grant insert, references, select, trigger, update on table public.domestic_help to anon;
grant insert, references, select, trigger, update on table public.domestic_help to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.eb_accounts to service_role;
grant insert, references, select, trigger, update on table public.eb_accounts to anon;
grant insert, references, select, trigger, update on table public.eb_accounts to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.eb_bills to service_role;
grant insert, references, select, trigger, update on table public.eb_bills to anon;
grant insert, references, select, trigger, update on table public.eb_bills to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.expenses to anon;
grant delete, insert, references, select, trigger, truncate, update on table public.expenses to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.expenses to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.guests to service_role;
grant insert, references, select, trigger, update on table public.guests to anon;
grant insert, references, select, trigger, update on table public.guests to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.house_photos to anon;
grant delete, insert, references, select, trigger, truncate, update on table public.house_photos to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.house_photos to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.houses to anon;
grant delete, insert, references, select, trigger, truncate, update on table public.houses to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.houses to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.identity_documents to service_role;
grant insert, references, select, trigger, update on table public.identity_documents to anon;
grant insert, references, select, trigger, update on table public.identity_documents to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.meter_readings to service_role;
grant insert, references, select, trigger, update on table public.meter_readings to anon;
grant insert, references, select, trigger, update on table public.meter_readings to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.move_in_records to service_role;
grant insert, references, select, trigger, update on table public.move_in_records to anon;
grant insert, references, select, trigger, update on table public.move_in_records to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.move_out_records to service_role;
grant insert, references, select, trigger, update on table public.move_out_records to anon;
grant insert, references, select, trigger, update on table public.move_out_records to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.notifications to service_role;
grant references, select, trigger on table public.notifications to anon;
grant references, select, trigger on table public.notifications to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.occupants to service_role;
grant insert, references, select, trigger, update on table public.occupants to anon;
grant insert, references, select, trigger, update on table public.occupants to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.payee_settings to anon;
grant delete, insert, references, select, trigger, truncate, update on table public.payee_settings to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.payee_settings to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.payment_allocations to service_role;
grant references, select, trigger on table public.payment_allocations to anon;
grant references, select, trigger on table public.payment_allocations to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.payments to service_role;
grant insert, references, select, trigger on table public.payments to anon;
grant insert, references, select, trigger on table public.payments to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.profiles to service_role;
grant references, select, trigger, truncate on table public.profiles to anon;
grant references, select, trigger, truncate on table public.profiles to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.properties to anon;
grant delete, insert, references, select, trigger, truncate, update on table public.properties to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.properties to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.property_members to anon;
grant delete, insert, references, select, trigger, truncate, update on table public.property_members to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.property_members to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.push_subscriptions to anon;
grant delete, insert, references, select, trigger, truncate, update on table public.push_subscriptions to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.push_subscriptions to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.receipt_counters to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.receipts to service_role;
grant references, select, trigger on table public.receipts to anon;
grant references, select, trigger on table public.receipts to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.reminder_rules to anon;
grant delete, insert, references, select, trigger, truncate, update on table public.reminder_rules to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.reminder_rules to service_role;
grant delete, insert, references, select, trigger, truncate, update on table public.rent_revisions to service_role;
grant insert, references, select, trigger on table public.rent_revisions to anon;
grant insert, references, select, trigger on table public.rent_revisions to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.scheduled_job_runs to service_role;
grant references, select, trigger on table public.scheduled_job_runs to anon;
grant references, select, trigger on table public.scheduled_job_runs to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.signatures to service_role;
grant references, select, trigger on table public.signatures to anon;
grant references, select, trigger on table public.signatures to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.tenancies to service_role;
grant insert, references, select, trigger, update on table public.tenancies to anon;
grant insert, references, select, trigger, update on table public.tenancies to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.tenancy_photos to service_role;
grant insert, references, select, trigger on table public.tenancy_photos to anon;
grant insert, references, select, trigger on table public.tenancy_photos to authenticated;
grant delete, insert, references, select, trigger, truncate, update on table public.tenants to service_role;
grant insert, references, select, trigger, update on table public.tenants to anon;
grant insert, references, select, trigger, update on table public.tenants to authenticated;
grant update (read_at) on table public.notifications to authenticated;
grant update (full_name, phone, preferred_language) on table public.profiles to authenticated;
grant select, update, usage on sequence public.activity_logs_id_seq to anon;
grant select, update, usage on sequence public.activity_logs_id_seq to authenticated;
grant select, update, usage on sequence public.activity_logs_id_seq to service_role;
grant select, update, usage on sequence public.complaint_code_seq to anon;
grant select, update, usage on sequence public.complaint_code_seq to authenticated;
grant select, update, usage on sequence public.complaint_code_seq to service_role;
grant select, update, usage on sequence public.complaint_updates_id_seq to anon;
grant select, update, usage on sequence public.complaint_updates_id_seq to authenticated;
grant select, update, usage on sequence public.complaint_updates_id_seq to service_role;
grant select, update, usage on sequence public.scheduled_job_runs_id_seq to anon;
grant select, update, usage on sequence public.scheduled_job_runs_id_seq to authenticated;
grant select, update, usage on sequence public.scheduled_job_runs_id_seq to service_role;
grant execute on function activate_agreement(uuid) to service_role;
grant execute on function activity_logs_immutable() to anon;
grant execute on function activity_logs_immutable() to authenticated;
grant execute on function activity_logs_immutable() to service_role;
grant execute on function add_team_to_new_property() to service_role;
grant execute on function agreement_tenancy_id(uuid) to anon;
grant execute on function agreement_tenancy_id(uuid) to authenticated;
grant execute on function agreement_tenancy_id(uuid) to service_role;
grant execute on function agreement_versions_after_insert() to anon;
grant execute on function agreement_versions_after_insert() to authenticated;
grant execute on function agreement_versions_after_insert() to service_role;
grant execute on function agreement_versions_before_insert() to anon;
grant execute on function agreement_versions_before_insert() to authenticated;
grant execute on function agreement_versions_before_insert() to service_role;
grant execute on function agreement_versions_before_update() to anon;
grant execute on function agreement_versions_before_update() to authenticated;
grant execute on function agreement_versions_before_update() to service_role;
grant execute on function agreement_visible_to_tenant(uuid) to anon;
grant execute on function agreement_visible_to_tenant(uuid) to authenticated;
grant execute on function agreement_visible_to_tenant(uuid) to service_role;
grant execute on function agreements_after_insert() to anon;
grant execute on function agreements_after_insert() to authenticated;
grant execute on function agreements_after_insert() to service_role;
grant execute on function agreements_before_update() to anon;
grant execute on function agreements_before_update() to authenticated;
grant execute on function agreements_before_update() to service_role;
grant execute on function agreements_daily(date) to service_role;
grant execute on function allocations_after_change() to anon;
grant execute on function allocations_after_change() to authenticated;
grant execute on function allocations_after_change() to service_role;
grant execute on function allocations_check() to anon;
grant execute on function allocations_check() to authenticated;
grant execute on function allocations_check() to service_role;
grant execute on function announcement_property(uuid) to anon;
grant execute on function announcement_property(uuid) to authenticated;
grant execute on function announcement_property(uuid) to service_role;
grant execute on function announcement_targets_me(text,uuid) to anon;
grant execute on function announcement_targets_me(text,uuid) to authenticated;
grant execute on function announcement_targets_me(text,uuid) to service_role;
grant execute on function announcement_visible(uuid) to anon;
grant execute on function announcement_visible(uuid) to authenticated;
grant execute on function announcement_visible(uuid) to service_role;
grant execute on function announcements_after_insert() to anon;
grant execute on function announcements_after_insert() to authenticated;
grant execute on function announcements_after_insert() to service_role;
grant execute on function announcements_before_insert() to anon;
grant execute on function announcements_before_insert() to authenticated;
grant execute on function announcements_before_insert() to service_role;
grant execute on function approve_agreement(uuid) to anon;
grant execute on function approve_agreement(uuid) to authenticated;
grant execute on function approve_agreement(uuid) to service_role;
grant execute on function approve_payment(uuid,jsonb) to anon;
grant execute on function approve_payment(uuid,jsonb) to authenticated;
grant execute on function approve_payment(uuid,jsonb) to service_role;
grant execute on function audit_row() to service_role;
grant execute on function auto_close_complaints(timestamp with time zone) to service_role;
grant execute on function cancel_receipt(uuid,text,boolean) to anon;
grant execute on function cancel_receipt(uuid,text,boolean) to authenticated;
grant execute on function cancel_receipt(uuid,text,boolean) to service_role;
grant execute on function charge_paid_paise(uuid) to anon;
grant execute on function charge_paid_paise(uuid) to authenticated;
grant execute on function charge_paid_paise(uuid) to service_role;
grant execute on function charges_after_edit() to anon;
grant execute on function charges_after_edit() to authenticated;
grant execute on function charges_after_edit() to service_role;
grant execute on function charges_after_status() to anon;
grant execute on function charges_after_status() to authenticated;
grant execute on function charges_after_status() to service_role;
grant execute on function charges_before_update() to anon;
grant execute on function charges_before_update() to authenticated;
grant execute on function charges_before_update() to service_role;
grant execute on function complaint_step(text) to anon;
grant execute on function complaint_step(text) to authenticated;
grant execute on function complaint_step(text) to service_role;
grant execute on function complaint_tenancy_id(uuid) to anon;
grant execute on function complaint_tenancy_id(uuid) to authenticated;
grant execute on function complaint_tenancy_id(uuid) to service_role;
grant execute on function complaints_after_change() to anon;
grant execute on function complaints_after_change() to authenticated;
grant execute on function complaints_after_change() to service_role;
grant execute on function complaints_before_insert() to anon;
grant execute on function complaints_before_insert() to authenticated;
grant execute on function complaints_before_insert() to service_role;
grant execute on function complaints_before_update() to anon;
grant execute on function complaints_before_update() to authenticated;
grant execute on function complaints_before_update() to service_role;
grant execute on function complete_move_in(uuid) to anon;
grant execute on function complete_move_in(uuid) to authenticated;
grant execute on function complete_move_in(uuid) to service_role;
grant execute on function confirm_complaint(uuid) to anon;
grant execute on function confirm_complaint(uuid) to authenticated;
grant execute on function confirm_complaint(uuid) to service_role;
grant execute on function deposit_guard() to anon;
grant execute on function deposit_guard() to authenticated;
grant execute on function deposit_guard() to service_role;
grant execute on function deposit_summary(uuid) to anon;
grant execute on function deposit_summary(uuid) to authenticated;
grant execute on function deposit_summary(uuid) to service_role;
grant execute on function disable_former_tenants(timestamp with time zone) to service_role;
grant execute on function documents_due_for_purge(date) to service_role;
grant execute on function eb_bills_after_insert() to anon;
grant execute on function eb_bills_after_insert() to authenticated;
grant execute on function eb_bills_after_insert() to service_role;
grant execute on function eb_bills_before_insert() to anon;
grant execute on function eb_bills_before_insert() to authenticated;
grant execute on function eb_bills_before_insert() to service_role;
grant execute on function generate_rent_charges(date) to service_role;
grant execute on function guest_checkout(uuid) to anon;
grant execute on function guest_checkout(uuid) to authenticated;
grant execute on function guest_checkout(uuid) to service_role;
grant execute on function guests_after_insert() to anon;
grant execute on function guests_after_insert() to authenticated;
grant execute on function guests_after_insert() to service_role;
grant execute on function guests_daily() to service_role;
grant execute on function guests_require_id() to anon;
grant execute on function guests_require_id() to authenticated;
grant execute on function guests_require_id() to service_role;
grant execute on function guests_retention() to anon;
grant execute on function guests_retention() to authenticated;
grant execute on function guests_retention() to service_role;
grant execute on function guests_set_status() to anon;
grant execute on function guests_set_status() to authenticated;
grant execute on function guests_set_status() to service_role;
grant execute on function handle_new_user() to service_role;
grant execute on function has_consent(uuid) to anon;
grant execute on function has_consent(uuid) to authenticated;
grant execute on function has_consent(uuid) to service_role;
grant execute on function house_property_id(uuid) to anon;
grant execute on function house_property_id(uuid) to authenticated;
grant execute on function house_property_id(uuid) to service_role;
grant execute on function house_timeline(uuid,bigint) to anon;
grant execute on function house_timeline(uuid,bigint) to authenticated;
grant execute on function house_timeline(uuid,bigint) to service_role;
grant execute on function houses_guard_status() to anon;
grant execute on function houses_guard_status() to authenticated;
grant execute on function houses_guard_status() to service_role;
grant execute on function identity_documents_guard() to anon;
grant execute on function identity_documents_guard() to authenticated;
grant execute on function identity_documents_guard() to service_role;
grant execute on function is_aal2() to anon;
grant execute on function is_aal2() to authenticated;
grant execute on function is_aal2() to service_role;
grant execute on function is_any_owner() to anon;
grant execute on function is_any_owner() to authenticated;
grant execute on function is_any_owner() to service_role;
grant execute on function is_house_owner(uuid) to anon;
grant execute on function is_house_owner(uuid) to authenticated;
grant execute on function is_house_owner(uuid) to service_role;
grant execute on function is_house_staff(uuid) to anon;
grant execute on function is_house_staff(uuid) to authenticated;
grant execute on function is_house_staff(uuid) to service_role;
grant execute on function is_my_house(uuid) to anon;
grant execute on function is_my_house(uuid) to authenticated;
grant execute on function is_my_house(uuid) to service_role;
grant execute on function is_my_open_tenancy(uuid) to anon;
grant execute on function is_my_open_tenancy(uuid) to authenticated;
grant execute on function is_my_open_tenancy(uuid) to service_role;
grant execute on function is_my_settlement(uuid) to anon;
grant execute on function is_my_settlement(uuid) to authenticated;
grant execute on function is_my_settlement(uuid) to service_role;
grant execute on function is_property_owner(uuid) to anon;
grant execute on function is_property_owner(uuid) to authenticated;
grant execute on function is_property_owner(uuid) to service_role;
grant execute on function is_property_staff(uuid) to anon;
grant execute on function is_property_staff(uuid) to authenticated;
grant execute on function is_property_staff(uuid) to service_role;
grant execute on function is_staff() to anon;
grant execute on function is_staff() to authenticated;
grant execute on function is_staff() to service_role;
grant execute on function is_tenancy_staff(uuid) to anon;
grant execute on function is_tenancy_staff(uuid) to authenticated;
grant execute on function is_tenancy_staff(uuid) to service_role;
grant execute on function is_tenant_staff(uuid) to anon;
grant execute on function is_tenant_staff(uuid) to authenticated;
grant execute on function is_tenant_staff(uuid) to service_role;
grant execute on function issue_receipt(uuid) to service_role;
grant execute on function log_action(text,text,text,uuid,jsonb) to authenticated;
grant execute on function log_action(text,text,text,uuid,jsonb) to service_role;
grant execute on function mark_agreement_generated(uuid) to anon;
grant execute on function mark_agreement_generated(uuid) to authenticated;
grant execute on function mark_agreement_generated(uuid) to service_role;
grant execute on function mark_overdue(date) to service_role;
grant execute on function meter_history(uuid) to anon;
grant execute on function meter_history(uuid) to authenticated;
grant execute on function meter_history(uuid) to service_role;
grant execute on function my_tenant_id() to anon;
grant execute on function my_tenant_id() to authenticated;
grant execute on function my_tenant_id() to service_role;
grant execute on function notifications_push() to anon;
grant execute on function notifications_push() to authenticated;
grant execute on function notifications_push() to service_role;
grant execute on function notify(uuid,text,jsonb,text,text) to service_role;
grant execute on function notify_property_staff(uuid,text,jsonb,text,text) to service_role;
grant execute on function payment_tenancy_id(uuid) to anon;
grant execute on function payment_tenancy_id(uuid) to authenticated;
grant execute on function payment_tenancy_id(uuid) to service_role;
grant execute on function payments_after_insert() to anon;
grant execute on function payments_after_insert() to authenticated;
grant execute on function payments_after_insert() to service_role;
grant execute on function payments_before_insert() to anon;
grant execute on function payments_before_insert() to authenticated;
grant execute on function payments_before_insert() to service_role;
grant execute on function properties_default_rules() to anon;
grant execute on function properties_default_rules() to authenticated;
grant execute on function properties_default_rules() to service_role;
grant execute on function property_id_for_row(text,jsonb) to service_role;
grant execute on function prorate(bigint,date,date) to anon;
grant execute on function prorate(bigint,date,date) to authenticated;
grant execute on function prorate(bigint,date,date) to service_role;
grant execute on function purge_documents(uuid[]) to service_role;
grant execute on function queue_reminders(date) to service_role;
grant execute on function recompute_charge_status(uuid) to service_role;
grant execute on function record_cash_payment(uuid,bigint,date,text,uuid,text) to anon;
grant execute on function record_cash_payment(uuid,bigint,date,text,uuid,text) to authenticated;
grant execute on function record_cash_payment(uuid,bigint,date,text,uuid,text) to service_role;
grant execute on function record_owner_eb_payment(uuid,date,date) to anon;
grant execute on function record_owner_eb_payment(uuid,date,date) to authenticated;
grant execute on function record_owner_eb_payment(uuid,date,date) to service_role;
grant execute on function register_guest(uuid,text,text,text,text,date,date,text,text,text,text) to anon;
grant execute on function register_guest(uuid,text,text,text,text,date,date,text,text,text,text) to authenticated;
grant execute on function register_guest(uuid,text,text,text,text,date,date,text,text,text,text) to service_role;
grant execute on function reject_payment(uuid,text) to anon;
grant execute on function reject_payment(uuid,text) to authenticated;
grant execute on function reject_payment(uuid,text) to service_role;
grant execute on function reminders_due(date) to anon;
grant execute on function reminders_due(date) to authenticated;
grant execute on function reminders_due(date) to service_role;
grant execute on function rent_for(uuid,date) to anon;
grant execute on function rent_for(uuid,date) to authenticated;
grant execute on function rent_for(uuid,date) to service_role;
grant execute on function reopen_complaint(uuid,text) to anon;
grant execute on function reopen_complaint(uuid,text) to authenticated;
grant execute on function reopen_complaint(uuid,text) to service_role;
grant execute on function reopen_settlement(uuid) to anon;
grant execute on function reopen_settlement(uuid) to authenticated;
grant execute on function reopen_settlement(uuid) to service_role;
grant execute on function report_deposits(uuid,uuid) to anon;
grant execute on function report_deposits(uuid,uuid) to authenticated;
grant execute on function report_deposits(uuid,uuid) to service_role;
grant execute on function report_eb(date,date,uuid,uuid) to anon;
grant execute on function report_eb(date,date,uuid,uuid) to authenticated;
grant execute on function report_eb(date,date,uuid,uuid) to service_role;
grant execute on function report_expenses(date,date,uuid,uuid) to anon;
grant execute on function report_expenses(date,date,uuid,uuid) to authenticated;
grant execute on function report_expenses(date,date,uuid,uuid) to service_role;
grant execute on function report_net_income(date,date,uuid,uuid) to anon;
grant execute on function report_net_income(date,date,uuid,uuid) to authenticated;
grant execute on function report_net_income(date,date,uuid,uuid) to service_role;
grant execute on function report_rent(date,date,uuid,uuid) to anon;
grant execute on function report_rent(date,date,uuid,uuid) to authenticated;
grant execute on function report_rent(date,date,uuid,uuid) to service_role;
grant execute on function respond_settlement(uuid,boolean,text) to anon;
grant execute on function respond_settlement(uuid,boolean,text) to authenticated;
grant execute on function respond_settlement(uuid,boolean,text) to service_role;
grant execute on function reverse_payment(uuid,text) to anon;
grant execute on function reverse_payment(uuid,text) to authenticated;
grant execute on function reverse_payment(uuid,text) to service_role;
grant execute on function run_job(text) to service_role;
grant execute on function send_agreement(uuid) to anon;
grant execute on function send_agreement(uuid) to authenticated;
grant execute on function send_agreement(uuid) to service_role;
grant execute on function set_agreement_status(uuid,text) to service_role;
grant execute on function set_receipt_pdf(uuid,text) to anon;
grant execute on function set_receipt_pdf(uuid,text) to authenticated;
grant execute on function set_receipt_pdf(uuid,text) to service_role;
grant execute on function settle_move_out(uuid,date,text,text) to anon;
grant execute on function settle_move_out(uuid,date,text,text) to authenticated;
grant execute on function settle_move_out(uuid,date,text,text) to service_role;
grant execute on function settlement_header(uuid) to anon;
grant execute on function settlement_header(uuid) to authenticated;
grant execute on function settlement_header(uuid) to service_role;
grant execute on function share_settlement(uuid) to anon;
grant execute on function share_settlement(uuid) to authenticated;
grant execute on function share_settlement(uuid) to service_role;
grant execute on function sign_agreement(uuid,text,text,text,text) to anon;
grant execute on function sign_agreement(uuid,text,text,text,text) to authenticated;
grant execute on function sign_agreement(uuid,text,text,text,text) to service_role;
grant execute on function staff_dashboard() to anon;
grant execute on function staff_dashboard() to authenticated;
grant execute on function staff_dashboard() to service_role;
grant execute on function staff_search(text) to anon;
grant execute on function staff_search(text) to authenticated;
grant execute on function staff_search(text) to service_role;
grant execute on function tenancies_after_status() to anon;
grant execute on function tenancies_after_status() to authenticated;
grant execute on function tenancies_after_status() to service_role;
grant execute on function tenancies_before_insert() to anon;
grant execute on function tenancies_before_insert() to authenticated;
grant execute on function tenancies_before_insert() to service_role;
grant execute on function tenancies_first_charge() to anon;
grant execute on function tenancies_first_charge() to authenticated;
grant execute on function tenancies_first_charge() to service_role;
grant execute on function tenancies_reenable_tenant() to anon;
grant execute on function tenancies_reenable_tenant() to authenticated;
grant execute on function tenancies_reenable_tenant() to service_role;
grant execute on function tenancies_status_machine() to anon;
grant execute on function tenancies_status_machine() to authenticated;
grant execute on function tenancies_status_machine() to service_role;
grant execute on function tenancy_property_id(uuid) to anon;
grant execute on function tenancy_property_id(uuid) to authenticated;
grant execute on function tenancy_property_id(uuid) to service_role;
grant execute on function tenancy_user_id(uuid) to service_role;
grant execute on function terminate_agreement(uuid,text) to anon;
grant execute on function terminate_agreement(uuid,text) to authenticated;
grant execute on function terminate_agreement(uuid,text) to service_role;
grant execute on function today_ist() to anon;
grant execute on function today_ist() to authenticated;
grant execute on function today_ist() to service_role;
grant execute on function update_complaint(uuid,text,text,text,text,text,bigint) to anon;
grant execute on function update_complaint(uuid,text,text,text,text,text,bigint) to authenticated;
grant execute on function update_complaint(uuid,text,text,text,text,text,bigint) to service_role;
grant execute on function usage_summary() to anon;
grant execute on function usage_summary() to authenticated;
grant execute on function usage_summary() to service_role;
grant execute on function version_agreement_id(uuid) to anon;
grant execute on function version_agreement_id(uuid) to authenticated;
grant execute on function version_agreement_id(uuid) to service_role;
grant execute on function view_agreement(uuid) to anon;
grant execute on function view_agreement(uuid) to authenticated;
grant execute on function view_agreement(uuid) to service_role;

-- TRUNCATE ignores row level security and the app never uses it.
revoke truncate on all tables in schema public from anon, authenticated;

-- Future migrations: same defaults as local Supabase (each migration still revokes what a role must not have).
alter default privileges for role postgres in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public grant all on sequences to anon, authenticated, service_role;
alter default privileges for role postgres in schema public grant execute on functions to anon, authenticated, service_role;
